# Exploring spatial filtering
See [correlate](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.correlate.html)

In [4]:
%matplotlib widget
import matplotlib.pyplot as plt
import scipy.ndimage as ndimage
import numpy as np

from scipy.ndimage import correlate
from skimage.filters import *
from scipy.stats import entropy

In [8]:
I = plt.imread('germanTown.jpg').astype('float')
I /= I.max()

In [15]:
def Info(arr):
    print(I.shape, I.max(), I.dtype)

In [21]:
plt.figure()
plt.imshow(I)
Info(I)
freq, bins = np.histogram(I[...,0].ravel(), bins=np.arange(257))
entropy(freq)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(363, 600, 3) 1.0 float64


0.06718684927718865

In [35]:
h = np.array([-1,1], ndmin=2).astype(np.int16)
h = np.stack([h,h,h], axis=-1)
print(h)
If = correlate(I.astype(np.int16),h)
plt.figure()
plt.imshow(If)

[[[-1 -1 -1]
  [ 1  1  1]]]


array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int16)

In [31]:
h = np.array([[-1., 0., 1], [-2, 0, 2], [-1, 0, 1]], dtype=np.float)
h

array([[-1.,  0.,  1.],
       [-2.,  0.,  2.],
       [-1.,  0.,  1.]])

In [ ]:
I.shape

In [ ]:
H = np.stack([h,h,h], axis=-1)

In [ ]:
H.shape

In [ ]:
Ih = correlate(I, H)

In [ ]:
f, ax = plt.subplots(1,2, figsize=(10,5), sharex=True, sharey=True)
ax[0].imshow(I)
ax[0].set_title('Original')
ax[1].imshow(Ih[...,0], cmap='gray')
ax[1].set_title('Filtered')

In [ ]:
Im = I[...,0]
Gx = correlate(Im, h)

In [ ]:
f, ax = plt.subplots(1,2, figsize=(10,5), sharex=True, sharey=True)
ax[0].imshow(Im, cmap='gray')
ax[0].set_title('Original')
ax[1].imshow(Gx, cmap='gray')
ax[1].set_title('Filtered')

In [ ]:
Gy = correlate(Im, h.transpose())

In [ ]:
Gm = Gx**2 + Gy**2

In [ ]:
f, ax = plt.subplots(1,3, figsize=(8,3), sharex=True, sharey=True)
ax[0].imshow(Im, cmap='gray')
ax[0].set_title('Original')
ax[1].imshow(Gx, cmap='gray')
ax[1].set_title('Gx')
ax[2].imshow(Gy, cmap='gray')
ax[2].set_title('Gy')

In [ ]:
f, ax = plt.subplots(1,2, figsize=(8,3), sharex=True, sharey=True)
ax[0].imshow(Im, cmap='gray')
ax[0].set_title('Original')
ax[1].imshow(np.sqrt(1+Gm), cmap='gray')

In [ ]:
Gx.max()

In [ ]:
np.max(Gm.ravel())

In [ ]:
plt.figure()
plt.imshow(Gm>.5)

In [ ]:
Gm.size

In [ ]:
np.sum(Gm>.5)