# Exploring spatial filtering
See [correlate](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.correlate.html)

In [1]:
%matplotlib widget
import matplotlib.pyplot as plt
import scipy.ndimage as ndimage
import numpy as np

from scipy.ndimage import correlate
from skimage.filters import *
from scipy.stats import entropy

In [2]:
I = plt.imread('germanTown.jpg').astype('float')
I /= I.max()

In [3]:
def Info(arr):
    print(I.shape, I.max(), I.dtype)

In [4]:
plt.figure()
plt.imshow(I)
Info(I)
freq, bins = np.histogram(I[...,0].ravel(), bins=np.arange(257))
entropy(freq)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(363, 600, 3) 1.0 float64


0.06718684927718865

In [5]:
h = np.array([-1,1], ndmin=2).astype(np.int16)
h = np.stack([h,h,h], axis=-1)
print(h)
If = correlate(I.astype(np.int16),h)
plt.figure()
plt.imshow(If)

[[[-1 -1 -1]
  [ 1  1  1]]]


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).


In [6]:
h = np.array([[-1., 0., 1], [-2, 0, 2], [-1, 0, 1]], dtype=np.float)
h

array([[-1.,  0.,  1.],
       [-2.,  0.,  2.],
       [-1.,  0.,  1.]])

In [7]:
I.shape

(363, 600, 3)

In [8]:
H = np.stack([h,h,h], axis=-1)

In [9]:
H.shape

(3, 3, 3)

In [10]:
Ih = correlate(I, H)

In [11]:
f, ax = plt.subplots(1,2, figsize=(10,5), sharex=True, sharey=True)
ax[0].imshow(I)
ax[0].set_title('Original')
ax[1].imshow(Ih[...,0], cmap='gray')
ax[1].set_title('Filtered')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Text(0.5, 1.0, 'Filtered')

In [12]:
Im = I[...,0]
Gx = correlate(Im, h)

In [13]:
f, ax = plt.subplots(1,2, figsize=(10,5), sharex=True, sharey=True)
ax[0].imshow(Im, cmap='gray')
ax[0].set_title('Original')
ax[1].imshow(Gx, cmap='gray')
ax[1].set_title('Filtered')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Text(0.5, 1.0, 'Filtered')

In [14]:
Gy = correlate(Im, h.transpose())

In [15]:
Gm = Gx**2 + Gy**2

In [16]:
f, ax = plt.subplots(1,3, figsize=(8,3), sharex=True, sharey=True)
ax[0].imshow(Im, cmap='gray')
ax[0].set_title('Original')
ax[1].imshow(Gx, cmap='gray')
ax[1].set_title('Gx')
ax[2].imshow(Gy, cmap='gray')
ax[2].set_title('Gy')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Text(0.5, 1.0, 'Gy')

In [17]:
f, ax = plt.subplots(1,2, figsize=(8,3), sharex=True, sharey=True)
ax[0].imshow(Im, cmap='gray')
ax[0].set_title('Original')
ax[1].imshow(np.sqrt(Gm), cmap='gray')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [18]:
Gx.max()

3.6941176470588237

In [19]:
np.max(Gm.ravel())

13.647489427143407

In [27]:
plt.figure()
#plt.imshow(Gm>.5)
plt.imshow(np.sqrt(Gm),cmap='jet')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [21]:
Gm.size

217800

In [22]:
np.sum(Gm>.5)

38144